### ISSUE TITLE
 Donation details are incomplete

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#45]
From J. Hegde:

ಚಂದಾ ಹಣ ಕಳುಹಿಸುವ ಕುರಿತು ಬ್ಯಾಂಕ್ ವಿವರಣೆ ಪೂರ್ತಿ ಆಗಿಲ್ಲ.

**Comment by arjunkashyap** [comment]
Account type : CLSB to be included along with the text following it.

**Comment by arjunkashyap** [comment]
You can send the amount through D.D./M.O. or E-Transfer. Bank details for E-Transfer -

Name of account  - Sambhashana Sandesha

Bank details: Corparation Bank, Girinagar, Bangalore

Acount  Type - CLSB

Ac.No – 074600301120001

MICR No – 560017055

IFSC No - CORP 0000746

[Account type CLSB  [This need not be mentioned  while mentioning the  account number. If there is a  column, asking for the account type, ONLY then, this should be mentioned. Otherwise please don’t.]
